function createfigure(X1, Y1, Parent1)
%CREATEFIGURE(X1, Y1, PARENT1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  PARENT1:  plot parent

%  Auto-generated by MATLAB on 03-Nov-2014 13:17:51

% Create figure
figure;

% polar currently does not support code generation, enter 'doc polar' for correct input syntax

% polar(...);

% Create plot
plot(X1,Y1,'Parent',Parent1,'LineStyle','--','Color',[1 0 0],...
    'DisplayName','3*cos(t)');

% Create title
title('Circunferencias');

% Create legend
legend(Parent1,'show');

