/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.Electrodomesticos;
import Logica.Producto;
import Logica.Viveres;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author estudiante
 */
public class JIproductos extends javax.swing.JInternalFrame {
ArrayList<Producto> ArrP;
ArrayList<Electrodomesticos> ArrE;
Producto objP;
String aux;
    /**
     * Creates new form JIproductos
     */
    public JIproductos() {
        initComponents();
        ArrP= new <Producto>ArrayList();
        ArrE= new <Electrodomesticos>ArrayList();
    }
    
     public JIproductos(ArrayList<Producto> arreP, ArrayList<Electrodomesticos> arrE) {
        initComponents();
        ArrP= arreP;
        ArrE= arrE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbOPC = new javax.swing.JComboBox();
        lblcodigo = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblvalorU = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtvaloru = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();

        setTitle("Agregar productos");

        cmbOPC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Viveres", "Electrodomesticos" }));
        cmbOPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOPCActionPerformed(evt);
            }
        });

        lblcodigo.setText("Codigo:");

        lblnombre.setText("Nombre");

        lblCantidad.setText("Cantidad:");

        lblvalorU.setText("Valor unitario:");

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbOPC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblvalorU)
                        .addGap(50, 50, 50)
                        .addComponent(txtvaloru))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCantidad)
                        .addGap(70, 70, 70)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblcodigo)
                        .addGap(80, 80, 80)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblnombre)
                        .addGap(80, 80, 80)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnagregar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbOPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvalorU)
                    .addComponent(txtvaloru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnagregar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOPCActionPerformed
        // TODO add your handling code here:
        aux= this.cmbOPC.getSelectedItem().toString();
    }//GEN-LAST:event_cmbOPCActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        objP = new Producto();
        this.objP.setCod(this.txtCodigo.getText());
        this.objP.setNombre(this.txtnombre.getText());
        this.objP.setCantudad(Integer.parseInt(this.txtcantidad.getText()));
        this.objP.setValoru(Integer.parseInt(this.txtvaloru.getText()));
        this.ArrP.add(objP);
        
        JOptionPane.showMessageDialog(this,"Ingresado correctamente"+ ArrP.toString()+"\n");
        this.dispose();
    }//GEN-LAST:event_btnagregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JComboBox cmbOPC;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblvalorU;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtvaloru;
    // End of variables declaration//GEN-END:variables
}
