/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.Electro;
import Logica.Viveres;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian
 */
public class JIProducto extends javax.swing.JInternalFrame {
    
    DefaultTableModel TablaE,TablaV;
    Viveres ObjV;
    Electro ObjE;
    ArrayList<Electro> LElectro;
    ArrayList<Viveres> LViveres;
    
    public JIProducto(ArrayList<Electro> LE, ArrayList<Viveres> LV) {
        
         initComponents();
         this.LElectro = LE;
         this.LViveres = LV;
         this.AsignarMT();
         
}
        /**
     * Creates new form JICliente
     */
    public JIProducto() {
        initComponents();
        }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblCant = new javax.swing.JLabel();
        lblValU = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        txtCodigoP = new javax.swing.JTextField();
        txtCantP = new javax.swing.JTextField();
        txtValU = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        lblCant1 = new javax.swing.JLabel();
        CboxTipo = new javax.swing.JComboBox();
        TPListas = new javax.swing.JTabbedPane();
        JPanelElectro = new javax.swing.JPanel();
        lblTituloE = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTElectro = new javax.swing.JTable();
        jPanelViveres = new javax.swing.JPanel();
        lblTiruloV = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTViveres = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        setTitle("Crear Producto");

        lblTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblTitulo.setText("Producto");

        lblNombre.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblNombre.setText("Nombre");

        lblID.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblID.setText("Codigo");

        lblCant.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblCant.setText("Cantidad");

        lblValU.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblValU.setText("Valor Unidad");

        txtCantP.setEnabled(false);

        btnCrear.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lblCant1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblCant1.setText("Tipo");

        CboxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Electrodomesticos", "Viveres" }));

        lblTituloE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblTituloE.setText("Lista Electrodomesticos");

        JTElectro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(JTElectro);

        javax.swing.GroupLayout JPanelElectroLayout = new javax.swing.GroupLayout(JPanelElectro);
        JPanelElectro.setLayout(JPanelElectroLayout);
        JPanelElectroLayout.setHorizontalGroup(
            JPanelElectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelElectroLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(lblTituloE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(JPanelElectroLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanelElectroLayout.setVerticalGroup(
            JPanelElectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelElectroLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TPListas.addTab("Electrodomesticos", JPanelElectro);

        lblTiruloV.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblTiruloV.setText("Lista Viveres");

        JTViveres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTViveres);

        javax.swing.GroupLayout jPanelViveresLayout = new javax.swing.GroupLayout(jPanelViveres);
        jPanelViveres.setLayout(jPanelViveresLayout);
        jPanelViveresLayout.setHorizontalGroup(
            jPanelViveresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViveresLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(lblTiruloV)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(jPanelViveresLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanelViveresLayout.setVerticalGroup(
            jPanelViveresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViveresLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTiruloV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TPListas.addTab("Viveres", jPanelViveres);

        btnSalir.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TPListas)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(lblTitulo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblCant1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblValU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(txtValU, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCantP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrear)
                            .addComponent(btnSalir))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(lblNombre)
                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant1)
                    .addComponent(CboxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValU)
                    .addComponent(txtValU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(TPListas, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        if(txtCodigoP.getText().trim().length()== 0 ||
                txtNombreP.getText().trim().length()== 0 ||
                txtValU.getText().trim().length()== 0 ||
                CboxTipo.getSelectedIndex() == 0){
            
        JOptionPane.showMessageDialog(this, "Complete todo el formulario");
        }
        
        else{
            String Datos1[] = { this.txtCodigoP.getText(),  this.txtNombreP.getText(), this.txtValU.getText()};
            try{    
            if(this.CboxTipo.getSelectedIndex() == 1){
                
                ObjE = new Electro();
                this.ObjE.setNombre(this.txtNombreP.getText());
                this.ObjE.setCodigo(this.txtCodigoP.getText());
                this.ObjE.setValor_Unidad(Double.parseDouble(this.txtValU.getText()));
                LElectro.add(ObjE);
                JOptionPane.showMessageDialog(this,"Los Datos del Producto Son : \n" + ObjE.toString());
                TablaE.addRow(Datos1);

                
            }
            else {
                
                ObjV = new Viveres();
                this.ObjV.setNombre(this.txtNombreP.getText());
                this.ObjV.setCodigo(this.txtCodigoP.getText());
                //this.ObjV.setCantidad(Integer.parseInt(this.txtCantP.getText()));
                this.ObjV.setValor_Unidad(Double.parseDouble(this.txtValU.getText()));
                LViveres.add(ObjV);
                JOptionPane.showMessageDialog(this,"Los Datos del Producto Son : \n" + ObjV.toString());
                TablaV.addRow(Datos1);
            }
        
        JOptionPane.showMessageDialog(this,"Producto Agregado");
                        }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Ingrese Un Precio Correcto");
                }
        txtCodigoP.setText("");
        txtNombreP.setText("");
        //txtCantP.setText("");
        txtValU.setText("");
        CboxTipo.setSelectedIndex(0);
        
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    private void AsignarMT(){
    
        TablaE = new DefaultTableModel();
         TablaV = new DefaultTableModel();
         String Titulos[] = {"Codigo_Producto","Nombre_Producto","Precio_Unidad"};
         this.TablaE.setColumnIdentifiers(Titulos);
         this.TablaV.setColumnIdentifiers(Titulos);
         this.JTElectro.setModel(TablaE);
         this.JTViveres.setModel(TablaV);
         Object[] Fila = new Object[TablaE.getColumnCount()];
         for(int i = 0 ; i < LElectro.size() ; i++){
             Fila[0] = LElectro.get(i).getCodigo();
             Fila[1] = LElectro.get(i).getNombre();
             Fila[2] = LElectro.get(i).getValor_Unidad();
             TablaE.addRow(Fila);
         }
         Object[] Fila1 = new Object[TablaV.getColumnCount()];
         for(int i = 0 ; i < LViveres.size() ; i++){
             Fila1[0] = LViveres.get(i).getCodigo();
             Fila1[1] = LViveres.get(i).getNombre();
             Fila1[2] = LViveres.get(i).getValor_Unidad();
             TablaV.addRow(Fila1);
             
         }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CboxTipo;
    private javax.swing.JPanel JPanelElectro;
    private javax.swing.JTable JTElectro;
    private javax.swing.JTable JTViveres;
    private javax.swing.JTabbedPane TPListas;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanelViveres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblCant1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTiruloV;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloE;
    private javax.swing.JLabel lblValU;
    private javax.swing.JTextField txtCantP;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtValU;
    // End of variables declaration//GEN-END:variables
}
