/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;
import Logica.DatosRegistro;
import javax.swing.JOptionPane;
/**
 *
 * @author estudiante
 */
public class Registro extends javax.swing.JFrame {
DatosRegistro obj;
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        obj=new DatosRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombre = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        lblvalorprestamo = new javax.swing.JLabel();
        lblporcentaje = new javax.swing.JLabel();
        lblplazomeses = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcredito = new javax.swing.JTextField();
        txtvalorprestamo = new javax.swing.JTextField();
        txtinteres = new javax.swing.JTextField();
        txtplazomeses = new javax.swing.JTextField();
        btningresar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnombre.setText("Nombre");

        lblnumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnumero.setText("No credito");

        lblvalorprestamo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblvalorprestamo.setText("Valor prestamo");

        lblporcentaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblporcentaje.setText("% de interes anual");

        lblplazomeses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblplazomeses.setText("plazo meses");

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtcredito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtvalorprestamo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtinteres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtplazomeses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btningresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btningresar.setText("ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        btnconsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnconsultar.setText("consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre)
                            .addComponent(lblplazomeses)
                            .addComponent(lblporcentaje)
                            .addComponent(lblvalorprestamo)
                            .addComponent(lblnumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre)
                            .addComponent(txtcredito)
                            .addComponent(txtvalorprestamo)
                            .addComponent(txtinteres)
                            .addComponent(txtplazomeses)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btningresar)
                        .addGap(35, 35, 35)
                        .addComponent(btnconsultar)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumero)
                    .addComponent(txtcredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvalorprestamo)
                    .addComponent(txtvalorprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblporcentaje)
                    .addComponent(txtinteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblplazomeses)
                    .addComponent(txtplazomeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btningresar)
                    .addComponent(btnconsultar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        // TODO add your handling code here:
       this.obj.setNombre(this.txtnombre.getText());
       this.obj.setNumcredto(this.txtcredito.getText());
        this.obj.setValor(Integer.parseInt(txtvalorprestamo.getText()));
        this.obj.setPorcentaje(Integer.parseInt(txtinteres.getText()));
        this.obj.setPlazo(Integer.parseInt(txtplazomeses.getText()));
        JOptionPane.showMessageDialog(this, "Datos ingresados correctamente");

    }//GEN-LAST:event_btningresarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Los datos son:\n"+obj.toString());
        
    }//GEN-LAST:event_btnconsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btningresar;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lblplazomeses;
    private javax.swing.JLabel lblporcentaje;
    private javax.swing.JLabel lblvalorprestamo;
    private javax.swing.JTextField txtcredito;
    private javax.swing.JTextField txtinteres;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtplazomeses;
    private javax.swing.JTextField txtvalorprestamo;
    // End of variables declaration//GEN-END:variables
}
