/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentación;

import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import lógica.Carro;
import lógica.Parqueadero;
import lógica.Tiempo;

/**
 *
 * @author Yair Lopez Poveda <ylopezp@correo.udistrital.edu.co>
 */
public class Formulario extends javax.swing.JFrame {

    public Parqueadero objPar = new Parqueadero();
    
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        valorM = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoResult = new javax.swing.JTextArea();
        ss = new javax.swing.JTextField();
        me = new javax.swing.JTextField();
        he = new javax.swing.JTextField();
        hs = new javax.swing.JTextField();
        ms = new javax.swing.JTextField();
        se = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parqueadero - Tarifa");

        jLabel2.setText("Hora de entrada :");

        jLabel3.setText("Hora de salida :");

        jLabel4.setText("Placa:");

        jLabel5.setText("Valor por minuto :");

        placa.setText(" ");
        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });

        valorM.setText("20");
        valorM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorMActionPerformed(evt);
            }
        });
        valorM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorMKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorMKeyTyped(evt);
            }
        });

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        campoResult.setEditable(false);
        campoResult.setColumns(20);
        campoResult.setRows(5);
        jScrollPane2.setViewportView(campoResult);

        ss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ssKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ssKeyTyped(evt);
            }
        });

        me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meActionPerformed(evt);
            }
        });
        me.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                meKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                meKeyTyped(evt);
            }
        });

        he.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heActionPerformed(evt);
            }
        });
        he.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                heKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                heKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heKeyTyped(evt);
            }
        });

        hs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hsKeyTyped(evt);
            }
        });

        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });
        ms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                msKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                msKeyTyped(evt);
            }
        });

        se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seActionPerformed(evt);
            }
        });
        se.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seKeyTyped(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Horas:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Segundos:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Minutos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(87, 87, 87))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(245, 245, 245)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(he, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorM, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(me, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(se, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(51, 51, 51))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {he, hs, me, ms, se, ss});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(me, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(he, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(se, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(valorM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {he, hs, me, ms, se, ss});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Carro aux = objPar.getObjCarro();
        aux.setPlaca(placa.getText());
        if(Integer.parseInt(he.getText())>Integer.parseInt(hs.getText())){
            JOptionPane.showMessageDialog(rootPane, "¡Error! La hora de entrada debe ser menor que la de salida.");
            he.setText("");
            me.setText("");
            se.setText("");
            hs.setText("");
            ms.setText("");
            ss.setText("");

        }else if(he.getText().trim().isEmpty() || me.getText().trim().isEmpty()|| 
                se.getText().trim().isEmpty()|| hs.getText().trim().isEmpty() || 
                ms.getText().trim().isEmpty() || ss.getText().trim().isEmpty() || 
                valorM.getText().trim().isEmpty() || placa.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "¡Error! Asegúrese de rellenar todos los campos.");
            he.setText("");
            me.setText("");
            se.setText("");
            hs.setText("");
            ms.setText("");
            ss.setText("");
            valorM.setText("");
        }else{
            objPar.setHoraEntrada(new Tiempo(Integer.parseInt(he.getText()),
            Integer.parseInt(me.getText()), Integer.parseInt(se.getText())));
            objPar.setHoraSalida(new Tiempo(Integer.parseInt(hs.getText()),
            Integer.parseInt(ms.getText()), Integer.parseInt(ss.getText())));
            objPar.setValorMin(Integer.parseInt(valorM.getText()));
            String aux1="";
            aux1+="Placa del vehículo: '"+objPar.objCarro.getPlaca()+"'\nHora de entrada: "+objPar.getHoraEntrada().toString()+"\n";
            aux1+="Hora de salida: "+objPar.getHoraSalida().toString()+"\n"+"Valor minuto: "+objPar.getValorMin()+"\n";
            aux1+="\nValor total a pagar: "+objPar.calcularTarifa();
            campoResult.setText(aux1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void valorMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorMActionPerformed

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msActionPerformed

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaActionPerformed

    private void heActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heActionPerformed
        
    }//GEN-LAST:event_heActionPerformed

    private void meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meActionPerformed

    private void heKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_heKeyTyped

    private void heKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heKeyReleased
        if(he.getText().trim().length()!=0){
//            if(he.getText().length()>2){
            if(he.getText().length()>2){
                he.setText("");
                Toolkit.getDefaultToolkit().beep();
            }else{
                if(Integer.parseInt(he.getText())>=24){
                    he.setText("");
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        }
    }//GEN-LAST:event_heKeyReleased

    private void heKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heKeyPressed
        
    }//GEN-LAST:event_heKeyPressed

    private void meKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meKeyReleased
        if(me.getText().trim().length()!=0){
            if(me.getText().length()>2){
                me.setText("");
                Toolkit.getDefaultToolkit().beep();
            }else{
                if(Integer.parseInt(me.getText())>=60){
                    me.setText("");
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        }
    }//GEN-LAST:event_meKeyReleased

    private void meKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_meKeyTyped

    private void seKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seKeyReleased
        if(se.getText().trim().length()!=0){
            if(se.getText().length()>2){
                se.setText("");
                Toolkit.getDefaultToolkit().beep();
            }else{
                if(Integer.parseInt(se.getText())>=60){
                    se.setText("");
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        }
    }//GEN-LAST:event_seKeyReleased

    private void seKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_seKeyTyped

    private void seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seActionPerformed
        
    }//GEN-LAST:event_seActionPerformed

    private void valorMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorMKeyReleased
        if(valorM.getText().trim().length()!=0){
            if(valorM.getText().length()>5){
                valorM.setText("");
                Toolkit.getDefaultToolkit().beep();
            }
        }
    }//GEN-LAST:event_valorMKeyReleased

    private void valorMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorMKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_valorMKeyTyped

    private void hsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hsKeyReleased
        if(hs.getText().trim().length()!=0){
            if(hs.getText().length()>2){
                hs.setText("");
                Toolkit.getDefaultToolkit().beep();
            }else{
                if(Integer.parseInt(hs.getText())>=24){
                    hs.setText("");
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        }
    }//GEN-LAST:event_hsKeyReleased

    private void hsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hsKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_hsKeyTyped

    private void msKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_msKeyTyped

    private void msKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msKeyReleased
        if(ms.getText().trim().length()!=0){
            if(ms.getText().length()>2){
                ms.setText("");
                Toolkit.getDefaultToolkit().beep();
            }else{
                if(Integer.parseInt(ms.getText())>=60){
                    ms.setText("");
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        }
    }//GEN-LAST:event_msKeyReleased

    private void ssKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_ssKeyTyped

    private void ssKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssKeyReleased
        if(ss.getText().trim().length()!=0){
            if(ss.getText().length()>2){
                ss.setText("");
                Toolkit.getDefaultToolkit().beep();
            }else{
                if(Integer.parseInt(ss.getText())>=60){
                    ss.setText("");
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        }
    }//GEN-LAST:event_ssKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoResult;
    private javax.swing.JTextField he;
    private javax.swing.JTextField hs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField me;
    private javax.swing.JTextField ms;
    private javax.swing.JTextField placa;
    private javax.swing.JTextField se;
    private javax.swing.JTextField ss;
    private javax.swing.JTextField valorM;
    // End of variables declaration//GEN-END:variables
}
