/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.Arreglo;
import Logica.Contacto;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class frameAgenda extends javax.swing.JFrame {
Arreglo objA;
    /**
     * Creates new form frameAgenda
     */
    public frameAgenda() {
        initComponents();
        objA= new Arreglo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresarC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDatosC = new javax.swing.JTextArea();
        btnBuscarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresarC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresarC.setText("Ingresar Contacto");
        btnIngresarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCActionPerformed(evt);
            }
        });

        jtaDatosC.setColumns(20);
        jtaDatosC.setRows(5);
        jScrollPane1.setViewportView(jtaDatosC);

        btnBuscarC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarC.setText("Buscar Contacto");
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresarC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(btnBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarC)
                    .addComponent(btnBuscarC))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCActionPerformed
        // TODO add your handling code here:
        this.jtaDatosC.removeAll();
        Contacto aux[] = objA.getObjC();
        for(int i=0; i< aux.length;i++){
            aux[i].setId(JOptionPane.showInputDialog("Digite Identificacion"+ (i+1)));
            aux[i].setNom(JOptionPane.showInputDialog("Digite Nombre"+(i+1)));
            aux[i].setTel(JOptionPane.showInputDialog("Digite Telefono"+(i+1)));
            aux[i].setEmail(JOptionPane.showInputDialog("Digite Email"+(i+1)));
        }
        this.jtaDatosC.append(this.objA.toString());
    }//GEN-LAST:event_btnIngresarCActionPerformed

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed
        // TODO add your handling code here:
        Contacto aux[] = objA.getObjC();
        String aux1 = JOptionPane.showInputDialog("Digite el ID del contacto a buscar");
        for(int i=0; i<aux.length;i++){
            if(aux1.equals(aux[i].getId())){
                JOptionPane.showMessageDialog(this,"Datos del Contacto"+ aux[i].toString());
            }
        }
    }//GEN-LAST:event_btnBuscarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnIngresarC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaDatosC;
    // End of variables declaration//GEN-END:variables
}
